name: Generate And Push Repros

on:
  schedule:
    - cron: '2 2 */1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup git user
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
      - name: Install dependencies
        run: YARN_ENABLE_IMMUTABLE_INSTALLS=false yarn install
      - name: Generate repros with Latest Storybook CLI
        run: yarn generate-repros --remote=https://gaetanmaisse:${{ secrets.PAT_GITHUB}}@github.com/storybookjs/repro-templates.git --push --force-push
      - name: Generate repros with Next Storybook CLI
        run: yarn generate-repros --next --remote=https://gaetanmaisse:${{ secrets.PAT_GITHUB}}@github.com/storybookjs/repro-templates.git --push --force-push
